package unam.dcct.view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;
import com.google.common.base.Strings;
import de.jreality.plugin.JRViewer;
import de.jreality.plugin.icon.ImageHook;
import de.jtem.jrworkspace.plugin.Controller;
import de.jtem.jrworkspace.plugin.PluginInfo;
import de.jtem.jrworkspace.plugin.sidecontainer.SideContainerPerspective;
import de.jtem.jrworkspace.plugin.sidecontainer.template.ShrinkPanelPlugin;
import unam.dcct.misc.Constants;
import unam.dcct.model.Model;
import unam.dcct.topology.SimplicialComplex;
import unam.dcct.view.geometry.GeometricComplex;

/**
 * Represents the output console that displays simplicial complex textual information
 * such as its set notation representation. 
 * @author Fausto
 *
 */
public class SCOutputConsole extends ShrinkPanelPlugin implements View{
	private JTextPane textPane = JRViewer.scriptingTextPane;
	private JScrollPane contentPanel = new JScrollPane();
	private final String newLine = "\n";
	// Text that is displayed in the console. 
	private StringBuilder complexInfo;
	private final String complexInfoFormat = 
			Constants.SIMPLICIAL_COMPLEX+ " information:" + newLine
			+ Constants.OUTPUT_CONSOLE_DELIMITER
			+ "Type:%s\n" // Initial or protocol
			+ "%s" // field for distributed computing model information
			+ "%s\n" // field for chromaticity information
			+ "Number of simplices: %d\n" 
			+ "Dimension of complex: %d\n" // field for complex dimension
			+ Constants.SET_NOTATION_REPRESENTATION + ":" + newLine
			+ "%s\n";
	private final String geometricInfoFormat = 
			newLine + Constants.GEOMETRIC_INFORMATION + newLine
			+ Constants.OUTPUT_CONSOLE_DELIMITER
			+ "Number of vertices: %d\n"
			+ "Number of triangles: %d\n";
	
	private static SCOutputConsole instance = null;

	/**
	 * Global point of access that returns the singleton instance of this class. 
	 * @return
	 */
	public static SCOutputConsole getInstance(){
		if (instance == null){
			instance = new SCOutputConsole();
		}
		return instance;
	}
	
	private SCOutputConsole() {
        setInitialPosition(ShrinkPanelPlugin.SHRINKER_BOTTOM);
	}
	
	private void createLayout() {
		Dimension d = new Dimension(400, 250);
        contentPanel.setPreferredSize(d);
        contentPanel.setMinimumSize(d);
        shrinkPanel.setLayout(new GridLayout());
        shrinkPanel.add(contentPanel);
        shrinkPanel.setShrinked(false);
        contentPanel.setViewportView(textPane);
        textPane.setText(Constants.SIMPLICIAL_COMPLEX_CONSOLE);
        textPane.setEditable(false);
        textPane.setCaretColor(Color.BLACK);
	}
	
	public void clearConsole(){
		complexInfo = null;
        textPane.setText("");
	}
	
	/**
	 * Builds the text that is displayed in the console. 
	 * @param complex Simplicial complex whose information is extracted in order to be displayed. 
	 * @param type type can 'initial complex' or 'protocol complex'. 
	 * @param modelInformation The current distributed computing model information. 
	 */
	private void setComplexInfo(SimplicialComplex complex, String type, String modelInformation){
		complexInfo = new StringBuilder(
				String.format(complexInfoFormat, type, 
						(!Strings.isNullOrEmpty(modelInformation)? 
								Constants.MODEL_INFORMATION + ":" + modelInformation : ""),
						(String.format("%s complex ", 
								(complex.isChromatic()? Constants.CHROMATIC : Constants.NON_CHROMATIC))),
						complex.getSimplices().size(),
						complex.dimension(),
						complex.toString()));
	}
	
	/**
	 * This is for jReality use. 
	 */
	@Override
	public void install(Controller c) throws Exception {
		super.install(c);
		//this.controller = c;
		createLayout();
	}

	/**
	 * This is for jReality use. 
	 */
	@Override
	public Class<? extends SideContainerPerspective> getPerspectivePluginClass() {
		return de.jreality.plugin.basic.View.class;
	}

	/**
	 * This is for jReality use. 
	 */
	@Override
	public PluginInfo getPluginInfo() {
		PluginInfo info = new PluginInfo();
		info.name = Constants.SIMPLICIAL_COMPLEX_CONSOLE;
		info.vendorName = "Fausto Salazar";
		info.icon = ImageHook.getIcon("select01.png");
		return info; 
	}
	
	/**
	 * When a simplicial complex is generated by the model, this is called 
	 * to write the new complex information into the console. 
	 */
	public void displayComplex() {
		clearConsole();
		Model m = Model.getInstance();
		SimplicialComplex protocolComplex = m.getProtocolComplex();
		// Check if the generated complex is initial
		if (protocolComplex==null){
			setComplexInfo(m.getInitialComplex(), Constants.INITIAL_COMPLEX, null);
		}else
		{
			String modelInfo = m.getCommunicationMechanism().toString() + newLine + "Round : " + m.getRoundCount() + newLine ;
			setComplexInfo(m.getProtocolComplex(), Constants.PROTOCOL_COMPLEX, modelInfo);
		}
		textPane.setText(complexInfo.toString());
	}
	
	/**
	 * It lets display geometric information (number of vertices, faces, etc) in the console.
	 * @param geom The geometric complex object whose information will be extracted to be displayed. 
	 */
	public void addGeometricInformation(GeometricComplex geom){
		if (geom!=null && complexInfo!=null){
			// Only count number of 2 dimension faces. 
			int totalFaces = 0;
			for (int[] face : geom.getFacesIndices()){
				if (face.length == 3)
					++totalFaces;
			}
			
			complexInfo.append(String.format(
					geometricInfoFormat, geom.getVertexCount(),totalFaces 
					));
			textPane.setText(complexInfo.toString());
		}
	}

	public void updateChromaticity() {
	}

	/**
	 * Clears the console
	 */
	public void reset() {
		clearConsole();
	}

}
